// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (db push, migrate, studio) need a direct, non-pooled
    // connection — PgBouncer's transaction pooling mode hangs on DDL.
    // The app's runtime PrismaClient (src/lib/prisma.ts) still uses
    // DATABASE_URL (pooled) via its own pg.Pool and is unaffected by this.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
